============================= test session starts =============================
platform win32 -- Python 3.12.3, pytest-8.3.2, pluggy-1.6.0 -- C:\Python312\python.exe
cachedir: .pytest_cache
rootdir: X:\pet_projs\FoodRadar2
configfile: pytest.ini
collecting ... collected 0 items

============================== warnings summary ===============================
C:\Python312\Lib\site-packages\_pytest\config\__init__.py:1437
  C:\Python312\Lib\site-packages\_pytest\config\__init__.py:1437: PytestConfigWarning: Unknown config option: DJANGO_SETTINGS_MODULE
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================= 1 warning in 0.00s ==============================
ERROR: file or directory not found: backend/tests/test_courier.py

